# Generated by Django 4.1.2 on 2023-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('jmbg', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('jmbg', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('short_major', models.CharField(max_length=2)),
                ('index_number', models.CharField(max_length=4)),
                ('year_of_enrollment', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
